image: registry.gitlab.example.com/kuber-infra/k8s-deploy
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay
  #CI_REGISTRY: registry.example.com
  #CI_REGISTRY_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH

before_script:
  - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"

stages:
  - build

pages:
  stage: build
  script:
    - mkdir -p charts
    - helm init --client-only
    - helm version --client
    - helm package . -d charts
    - cd charts
    - helm repo index . --url https://dmitrievav.github.io/helmcharts
    - cat index.yaml
  artifacts:
    paths:
    - charts
  only:
    - master
