apiVersion: v1
entries:
  simpleapp:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-11-11T11:26:28.507447134-05:00
    description: A simple app deployment for Kubernetes
    digest: 6cf73c6cd9ecf2ddcbc85cfc0ddea7e1c81dbd7abc5e671026f1b825cf1a4fb8
    name: simpleapp
    urls:
    - https://dmitrievav.github.io/helm/charts/simpleapp-0.1.0.tgz
    version: 0.1.0
  statefulapp:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-11-11T11:26:28.507639204-05:00
    description: A stateful app deployment for Kubernetes
    digest: 3de1f20cc0f4994d5a65989b1894078d0106e77ba260d085014e71e085af0c63
    name: statefulapp
    urls:
    - https://dmitrievav.github.io/helm/charts/statefulapp-0.1.0.tgz
    version: 0.1.0
generated: 2018-11-11T11:26:28.507023488-05:00
