apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: {{ template "helmchart.name" . }}
    chart: {{ template "helmchart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "helmchart.fullname" . }}
spec:
  ports:
  - name: "fake"
    port: 55555
    targetPort: 0
  clusterIP: None
  selector:
    k8s-app: {{ template "helmchart.name" . }}
    release: {{ .Release.Name }}
